server:
  port: 7900
spring:
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
  datasource:
    platform: h2
    schema: classpath:schema.sql
    data: classpath:data.sql
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.type.description.sql.BasicBinder: trace
    org.hibernate.type.description.sql.BasicExtractor: trace
    com.vi: debug

