
server:
  port: 7901
eureka:
  client:
    service-url:
#      defaultZone: http://vi:123@localhost:8761/eureka
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
spring:
  application:
    name: microservice-consumer-movie
logging:
  level:
    com.vi.cloud.feign.UserFeignClient: DEBUG
